<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Route conventions
    |--------------------------------------------------------------------------
    | name_prefix is prepended to every CRUD route name generated by the
    | Route::crud() macro and used by CrudController to resolve redirects.
    */
    'route' => [
        'name_prefix' => 'admin.',
    ],

    /*
    |--------------------------------------------------------------------------
    | View conventions
    |--------------------------------------------------------------------------
    | path_prefix is prepended to a controller's $viewPath when resolving the
    | index/create/edit/show Blade views.
    */
    'views' => [
        'path_prefix' => 'backend.pages.',
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission gating
    |--------------------------------------------------------------------------
    | When enabled, the Route::crud() macro wraps each action in a
    | `permission:{action}-{resource}` middleware (e.g. list-user, create-user),
    | and admin-core:make creates the matching permission rows via `model`.
    | Set enabled to false to register routes without permission middleware.
    */
    'permission' => [
        'enabled' => true,
        'pattern' => '{action}-{resource}',
        'model' => \Spatie\Permission\Models\Permission::class,
        'role_model' => \Spatie\Permission\Models\Role::class,
        // admin-core:make grants each new resource's permissions to this role so
        // it's usable immediately (no AccessSeeder re-run). Set null to disable.
        'super_role' => 'admin',
    ],

    /*
    |--------------------------------------------------------------------------
    | Default DataTables page length
    |--------------------------------------------------------------------------
    */
    'pagination' => 50,

    /*
    |--------------------------------------------------------------------------
    | Generator
    |--------------------------------------------------------------------------
    | uuid: when true, `admin-core:make` uses the *hybrid* key strategy — a fast
    | bigint `id` primary key (lean foreign keys + joins) plus a unique public
    | `uuid` column used in URLs/APIs (non-enumerable). Override per-resource with
    | the --uuid / --no-uuid flags.
    */
    'generator' => [
        'uuid' => false,
        'audit' => false,
    ],

];
