<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Route conventions
    |--------------------------------------------------------------------------
    | name_prefix is prepended to every CRUD route name generated by the
    | Route::crud() macro and used by CrudController to resolve redirects.
    */
    'route' => [
        'name_prefix' => 'admin.',
    ],

    /*
    |--------------------------------------------------------------------------
    | View conventions
    |--------------------------------------------------------------------------
    | path_prefix is prepended to a controller's $viewPath when resolving the
    | index/create/edit/show Blade views.
    */
    'views' => [
        'path_prefix' => 'backend.pages.',
    ],

    /*
    |--------------------------------------------------------------------------
    | Sidebar menu
    |--------------------------------------------------------------------------
    | The admin sidebar is data-driven: <x-admin-core::sidebar-menu /> renders this
    | array, dropping any item the current user can't reach (its `can` permission
    | fails, or its `route` doesn't exist) and any section header left empty.
    |
    | Item shapes:
    |   ['label' => 'Products', 'route' => 'admin.products.index',
    |    'icon' => 'bi bi-box', 'can' => 'list-product', 'match' => 'admin/products*']
    |   ['header' => 'Access']                                  // a section label
    |   ['label' => 'Access', 'icon' => '…', 'match' => 'admin/x/*',
    |    'children' => [ …items… ]]                             // a collapsible group
    |
    | `admin-core:make` appends new resources at the `admin-core:menu` marker below.
    | (Run `php artisan config:clear` after generating if you cache config.)
    */
    'menu' => [
        ['label' => 'Dashboard', 'route' => 'admin.dashboard', 'icon' => 'bi bi-speedometer2', 'match' => 'admin'],
        // admin-core:menu
        ['header' => 'Access'],
        ['label' => 'Assessments', 'icon' => 'bi bi-people', 'match' => 'admin/assessments/*', 'children' => [
            ['label' => 'Users', 'route' => 'admin.assessments.users.index', 'icon' => 'bi bi-person', 'can' => 'list-user', 'match' => 'admin/assessments/users*'],
            ['label' => 'Roles', 'route' => 'admin.assessments.roles.index', 'icon' => 'bi bi-shield-lock', 'can' => 'list-role', 'match' => 'admin/assessments/roles*'],
            ['label' => 'Group Permissions', 'route' => 'admin.assessments.group_permissions.index', 'icon' => 'bi bi-diagram-3', 'can' => 'list-group-permission', 'match' => 'admin/assessments/group_permissions*'],
            ['label' => 'Permissions', 'route' => 'admin.assessments.permissions.index', 'icon' => 'bi bi-key', 'can' => 'list-permission', 'match' => 'admin/assessments/permissions*'],
        ]],
        ['header' => 'System'],
        ['label' => 'Media', 'route' => 'admin.media.index', 'icon' => 'bi bi-images', 'can' => 'manage-media', 'match' => 'admin/media*'],
        ['label' => 'Approvals', 'route' => 'admin.approvals.index', 'icon' => 'bi bi-check2-square', 'can' => 'list-approval', 'match' => 'admin/approvals*'],
        ['label' => 'Settings', 'route' => 'admin.settings.index', 'icon' => 'bi bi-gear', 'can' => 'manage-settings', 'match' => 'admin/settings*'],
        ['label' => 'Activity Log', 'route' => 'admin.activity-logs.index', 'icon' => 'bi bi-clock-history', 'can' => 'list-activity', 'match' => 'admin/activity-logs*'],
        ['label' => 'Error Log', 'route' => 'admin.error-logs.index', 'icon' => 'bi bi-bug', 'can' => 'view-error-log', 'match' => 'admin/error-logs*'],
        ['label' => 'Menu', 'route' => 'admin.menu.index', 'icon' => 'bi bi-list-nested', 'can' => 'manage-menu', 'match' => 'admin/menu*'],
        ['label' => 'Documentation', 'route' => 'admin.docs', 'icon' => 'bi bi-book', 'match' => 'admin/docs'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Sidebar menu source
    |--------------------------------------------------------------------------
    | 'config'   (default) — render the `menu` array above.
    | 'database' — render the menu_items table managed at /admin/menu (the Menu
    |              manager, shipped by --access) via <x-admin-core::sidebar-menu>,
    |              cached and permission/route-filtered exactly like the config menu.
    |
    | Switching keeps everything else the same. Seed the table from your current
    | array with:  php artisan admin-core:menu:import
    */
    'menu_source' => env('ADMIN_CORE_MENU_SOURCE', 'config'),

    /*
    |--------------------------------------------------------------------------
    | Extra portals (named menus) — multi-portal
    |--------------------------------------------------------------------------
    | A second admin area (merchant, vendor, reseller, …) renders its own menu with
    | <x-admin-core::sidebar-menu menu="merchant" guard="merchant" />. Pass the portal's
    | auth `guard` so the `can` checks run against that portal's user. Each named menu
    | keeps its own `// admin-core:menu:<name>` marker, which `admin-core:make
    | Order --menu=merchant` appends to. Uncomment and tailor to your portals:
    */
    'menus' => [
        // 'merchant' => [
        //     ['label' => 'Dashboard', 'route' => 'merchant.dashboard', 'icon' => 'bi bi-shop', 'match' => 'merchant'],
        //     // admin-core:menu:merchant
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission gating
    |--------------------------------------------------------------------------
    | When enabled, the Route::crud() macro wraps each action in a
    | `permission:{action}-{resource}` middleware (e.g. list-user, create-user),
    | and `admin-core:sync-permissions` creates the matching permission rows via `model` (make is
    | filesystem-only and never touches the database).
    | Set enabled to false to register routes without permission middleware.
    */
    'permission' => [
        'enabled' => true,
        'pattern' => '{action}-{resource}',
        'model' => \Spatie\Permission\Models\Permission::class,
        'role_model' => \Spatie\Permission\Models\Role::class,
        // `admin-core:sync-permissions` grants each resource's permissions to this role so it's usable
        // immediately (make itself is filesystem-only and never touches the database). Set null to disable.
        'super_role' => 'admin',
        // Roles `admin-core:sync-permissions` grants to. Empty = just the (per-guard) super_role above.
        // Set to grant several roles, e.g. ['admin', 'super-admin']. The --role option overrides this per run.
        'default_roles' => [],
        // Default guard for generated permissions + route gates. `admin-core:make --guard=…`
        // overrides per resource (multi-portal). Spatie scopes permissions by guard.
        'guard' => 'web',
        // Per-guard overrides for separate-portal guards. Spatie requires the super role to
        // be on the same guard as the permission, so a portal can name its own:
        //   'guards' => ['merchant' => ['super_role' => 'merchant-admin']],
        'guards' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Approval workflow (maker-checker)
    |--------------------------------------------------------------------------
    | Actions marked ->requiresApproval() file a pending request the Approvals
    | inbox decides. By default the REQUESTER can never approve their own request
    | (segregation of duties), even if they hold the approve permission. Set true
    | only for a workflow that intentionally allows self-approval.
    */
    'approval' => [
        'allow_self_approval' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Two-factor authentication (TOTP)
    |--------------------------------------------------------------------------
    | Opt-in authenticator-app 2FA for the admin login (Google Authenticator / Authy). Off by default,
    | so existing installs are unaffected. With 'enabled' on, each admin can turn 2FA on from their
    | profile; the login then asks for a 6-digit code (or a single-use recovery code). Set 'enforce' to
    | require it — admins without confirmed 2FA are redirected to set it up. Needs the --access kit
    | (the user trait, the two_factor columns migration, and the profile routes).
    */
    'two_factor' => [
        'enabled' => env('ADMIN_CORE_2FA', false),
        'enforce' => env('ADMIN_CORE_2FA_ENFORCE', false),
        // TOTP drift tolerance — each unit is one ±30s window either side of "now".
        'window' => 1,
        // Number of single-use recovery codes generated when 2FA is enabled.
        'recovery_codes' => 8,
    ],

    /*
    |--------------------------------------------------------------------------
    | Default DataTables page length
    |--------------------------------------------------------------------------
    */
    'pagination' => 50,

    /*
    |--------------------------------------------------------------------------
    | Max DataTables page length (list getData safety cap)
    |--------------------------------------------------------------------------
    | The hard ceiling on the list endpoint's `length` — a client requesting
    | `?length=-1` (show all) or a huge value is capped to this, so one request
    | can't fetch + serialise the whole table into memory. Mirrors the JSON
    | API's `api.max_per_page`.
    */
    'pagination_max' => 500,

    /*
    |--------------------------------------------------------------------------
    | Forms
    |--------------------------------------------------------------------------
    | idempotency: generated create forms carry a one-time <x-admin-core::idempotency-key /> token, and
    | WebController::store() short-circuits a repeated submit (double-click / browser retry) carrying the same
    | token instead of creating a duplicate — no per-resource column needed (the token is held briefly in the
    | cache). idempotency_ttl is how long (minutes) a token is remembered. Best-effort on the `file` cache driver
    | (no atomic add); use redis/memcached/database for strict dedup under true concurrency.
    */
    'forms' => [
        'idempotency' => true,
        'idempotency_ttl' => 5,
    ],

    /*
    |--------------------------------------------------------------------------
    | Money (the `money` field type)
    |--------------------------------------------------------------------------
    | A `price:money` field stores an integer count of MINOR units (cents/sen) so amounts and sums stay
    | exact — no binary-float rounding (0.1 + 0.2 !== 0.3). `currency` is the default; each entry under
    | `currencies` says how that currency stores + displays:
    |   decimals  how many minor units make one major unit — USD = 2 ($15.00 → 1500), KHR = 0 (៛15,000 → 15000)
    |   symbol    the currency sign            position  'before' ($15) or 'after' (15 €)
    |   thousands group separator              decimal   the decimal point character
    | Pin one column to a non-default currency in the DSL: `price:money:KHR`. A currency not listed here still
    | works (symbol = its code, 2 decimals). See \Ngos\AdminCore\Support\Money.
    */
    'money' => [
        'currency' => env('ADMIN_CORE_CURRENCY', 'USD'),
        'currencies' => [
            'USD' => ['symbol' => '$', 'decimals' => 2, 'position' => 'before', 'thousands' => ',', 'decimal' => '.'],
            'KHR' => ['symbol' => '៛', 'decimals' => 0, 'position' => 'before', 'thousands' => ',', 'decimal' => '.'],
            'EUR' => ['symbol' => '€', 'decimals' => 2, 'position' => 'after', 'thousands' => '.', 'decimal' => ','],
            'GBP' => ['symbol' => '£', 'decimals' => 2, 'position' => 'before', 'thousands' => ',', 'decimal' => '.'],
            'JPY' => ['symbol' => '¥', 'decimals' => 0, 'position' => 'before', 'thousands' => ',', 'decimal' => '.'],
            'THB' => ['symbol' => '฿', 'decimals' => 2, 'position' => 'before', 'thousands' => ',', 'decimal' => '.'],
            'VND' => ['symbol' => '₫', 'decimals' => 0, 'position' => 'after', 'thousands' => '.', 'decimal' => ','],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Global search (<x-admin-core::global-search /> + Route::adminCoreSearch())
    |--------------------------------------------------------------------------
    | A dependency-free, offline-friendly LIKE search across the resources you list here — no Scout /
    | external engine. Add the topbar box with <x-admin-core::global-search /> and call
    | Route::adminCoreSearch() inside your admin route group. Each entry:
    |   ['model' => \App\Models\Product::class, 'columns' => ['name'], 'label' => 'Products',
    |    'route' => 'admin.products.edit', 'key' => 'uuid', 'icon' => 'bi bi-box-seam']
    | columns are LIKE-matched (a translatable JSON column works — its text is matched, label uses the
    | active locale); route+key build the result link (key defaults to the model's primary key).
    */
    'search' => [],

    /*
    |--------------------------------------------------------------------------
    | Dashboard (<x-admin-core::dashboard /> widget framework)
    |--------------------------------------------------------------------------
    | Drop <x-admin-core::dashboard /> into your dashboard view and declare the widgets here. A widget is
    | either a class extending Ngos\AdminCore\Dashboard\Widgets\{StatWidget|ChartWidget|ListWidget} (or the
    | base Widget for a custom partial), or — for simple cases — an inline config array. Each widget receives a
    | DashboardContext carrying the active date range (the toolbar preset / ?from=&to=) so it can scope its
    | own queries and compare against the previous period for a trend arrow. Everything below is YOUR app's
    | data — the package only lays the widgets out, so this is fully app-agnostic.
    |
    |   'widgets' => [
    |       \App\Dashboard\RevenueWidget::class,                              // a class widget (config-cache safe)
    |       ['type' => 'stat', 'title' => 'Active', 'icon' => 'bi-people',    // an inline widget WITHOUT closures
    |        'value' => 42, 'link' => '/admin/users'],
    |   ],
    |
    | IMPORTANT — closures + `php artisan config:cache`: a widget with a CLOSURE (an inline
    | `'value' => fn ($c) => …`) must NOT live in this config array, because `config:cache` serialises the
    | config with var_export and fatals on a Closure ("Call to undefined method Closure::__set_state()"),
    | breaking the whole app. Put closure widgets in a class widget (extend StatWidget/ChartWidget/ListWidget)
    | OR register them at runtime from a service provider's boot(), which runs even when the config is cached:
    |
    |   // app/Providers/AppServiceProvider::boot()
    |   \Ngos\AdminCore\Dashboard\Dashboard::register([
    |       'type' => 'stat', 'title' => 'Users', 'icon' => 'bi-people',
    |       'value'    => fn ($c) => \App\Models\User::query()->tap(fn ($q) => $c->scope($q))->count(),
    |       'previous' => fn ($c) => \App\Models\User::query()->tap(fn ($q) => $c->scopePrevious($q))->count(),
    |       'link'     => '/admin/users',
    |   ]);
    */
    'dashboard' => [
        'widgets' => [],
        'default_range' => '30d',  // today | 7d | 30d | month | all
        'date_filter' => true,     // show the date-range toolbar
        'customizable' => true,    // let each user drag-reorder + hide their widgets (saved per user)
    ],

    /*
    |--------------------------------------------------------------------------
    | Notifications
    |--------------------------------------------------------------------------
    | In-app notifications are always on (the bell + /admin/notifications, Laravel
    | database notifications). Set `realtime` to true to ALSO broadcast each
    | AdminNotification so the bell updates live + a toast pops on arrival — this
    | needs a broadcaster (Reverb/Pusher) + Laravel Echo + a running queue worker.
    | See the "Realtime notifications" section in the README. Per-notification
    | override: new AdminNotification(..., broadcast: true|false).
    */
    'notifications' => [
        'realtime' => env('ADMIN_CORE_REALTIME', false),

        // Notification Platform channel drivers: a `name => Driver::class` map the NotificationChannelManager
        // seeds from. A host or module also registers channels at runtime via ->extend() from a provider's boot().
        'channels' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Uploads (images & files) — compression + storage/CDN
    |--------------------------------------------------------------------------
    | All image/file uploads (avatars, `image`/`file` fields, settings images) go
    | through Ngos\AdminCore\Support\Media, so storage + URLs are configured here.
    |
    | disk      : filesystem disk to store on (config/filesystems.php). Point it at
    |             s3 (+ CloudFront) to serve from a CDN automatically.
    | cdn_url   : optional absolute base URL prepended to stored paths when building
    |             URLs (front your storage with a CDN without changing the disk).
    |             Overrides the disk's own url(). e.g. https://cdn.example.com
    | compress  : re-encode uploaded images to WebP (best size at high quality).
    |             Falls back to storing the original if encoding isn't possible.
    | max_width : downscale images wider than this (px) before encoding; 0 = no cap.
    | quality   : WebP quality (0–100); ~82 is visually lossless at a big size saving.
    */
    'uploads' => [
        'disk' => env('ADMIN_CORE_UPLOAD_DISK', 'public'),
        'cdn_url' => env('ADMIN_CORE_CDN_URL'),
        'compress' => true,
        'max_width' => 1600,
        'quality' => 82,
        'max_kb' => 12288, // per-file size cap for the media library uploader (12 MB)
        // The media library upload allowlist. NEVER includes executable/markup types (php, phtml, svg, html…)
        // — they would be served from the public disk (stored XSS / RCE). Widen per project if you need more.
        'allowed_mimes' => 'jpg,jpeg,png,webp,gif,pdf,doc,docx,xls,xlsx,csv,txt,zip',
        // Media library visibility (the browse/list/delete screen behind Route::adminCoreMedia()):
        //   'shared' (default) — one global pool every `manage-media` holder browses and can delete from
        //                        (the classic WordPress-style shared library; correct for a single admin team).
        //   'own'              — each user sees, and can delete, only the items THEY uploaded (scoped by
        //                        user_id). Also walls off one portal's / tenant's uploads from another's —
        //                        opt in for a multi-portal or multi-tenant install to close the cross-user IDOR.
        'media_scope' => 'shared',
    ],

    /*
    |--------------------------------------------------------------------------
    | Translation & multi-language
    |--------------------------------------------------------------------------
    | Two features, both driven by middleware (no public translate endpoint):
    |
    |  • Per-user UI language — SetLocale middleware picks the active language from
    |    the signed-in user's `locale` (when a `users.locale` column exists), else
    |    the session, else `default`. Users switch via a link `?setlang=km`, which
    |    the same middleware persists. So one admin runs in English, another in
    |    Khmer, each remembered per user.
    |
    |  • Content auto-translate — AutoTranslate middleware fills empty per-locale
    |    fields on save (e.g. you type a product name in Khmer, English/Thai/… are
    |    filled in for you). It never overwrites what you typed, and runs INSIDE the
    |    authenticated, CSRF-protected form submit — no extra endpoint to secure.
    |
    | locales : every language the admin offers — add as many as you like. The key
    |           is the ISO code used by Laravel + the translator (en, km, th, vi, zh…).
    | driver  : which translation backend to use. `mymemory` is free + needs no key.
    |           `libretranslate` (self-host) keeps data on your own servers (private).
    |           `null` disables auto-translate (UI language still works).
    | max_length / rate_limit / timeout : safety limits for outbound translate calls.
    | API keys live here (from env), server-side only — never exposed to the browser.
    */
    'translation' => [
        'enabled' => env('ADMIN_CORE_TRANSLATION', true),
        'driver' => env('ADMIN_CORE_TRANSLATOR', 'mymemory'), // mymemory | libretranslate | null
        'default' => env('ADMIN_CORE_LOCALE', 'en'),
        'locales' => [
            'en' => 'English',
            'km' => 'ខ្មែរ',
            // 'th' => 'ไทย', 'vi' => 'Tiếng Việt', 'zh' => '中文', 'fr' => 'Français',
        ],
        'max_length' => 5000,    // reject translate input longer than this
        'rate_limit' => 60,      // max outbound translate calls per request (guards a runaway save)
        'timeout' => 8,          // seconds per provider call
        'mymemory' => [
            'email' => env('MYMEMORY_EMAIL'), // optional — raises the free daily quota
        ],
        'libretranslate' => [
            'url' => env('LIBRETRANSLATE_URL', 'https://libretranslate.com'),
            'key' => env('LIBRETRANSLATE_KEY'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Error log retention (--access)
    |--------------------------------------------------------------------------
    | Captured exceptions older than this many days are pruned. The package
    | registers a daily `model:prune` for the ErrorLog model, so this needs the
    | app's scheduler running (`schedule:run` via cron). Set to 0 to keep errors
    | forever (no pruning). You can also prune on demand:
    |   php artisan model:prune --model="Ngos\AdminCore\Models\ErrorLog"
    */
    'error_log' => [
        'retention_days' => 30,

        // Query-string parameters whose VALUE is masked to [redacted] before an error's URL is stored, so a
        // secret in the URL of a failing request (a password-reset ?token=/?email=, an ?api_token=) doesn't
        // sit in the admin-viewable error_logs table. Matched case-insensitively. The stack trace is stored
        // WITHOUT call arguments regardless (PHP inlines string args, which can be passwords/tokens).
        'redact' => [
            'token', '_token', 'api_token', 'access_token', 'refresh_token', 'secret', 'api_key', 'key',
            'password', 'password_confirmation', 'otp', 'code', 'email',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Activity log retention (--audit)
    |--------------------------------------------------------------------------
    | Audit rows older than this many days are pruned by a daily `model:prune`
    | (needs the app's scheduler cron). Defaults to 0 = keep FOREVER, the safe
    | choice for an audit trail — set a positive number to opt in. On demand:
    |   php artisan model:prune --model="Ngos\AdminCore\Models\ActivityLog"
    */
    'activity_log' => [
        'retention_days' => 0,
    ],

    /*
    |--------------------------------------------------------------------------
    | API (--api)
    |--------------------------------------------------------------------------
    | Resources generated with --api expose a JSON API (JsonResource + apiResource
    | routes) for a decoupled front-end (Nuxt, mobile, …). The public identifier is
    | always the uuid route key, never the bigint id. `middleware` guards every API
    | route — Sanctum + a 60/min rate limit by default; add a tenant-scoping
    | middleware here for a multi-tenant setup, or tune `throttle:` for your load
    | (raise it, swap in a named limiter, or drop it). `per_page` is the default
    | index page size (override with ?per_page=).
    */
    'api' => [
        // throttle:60,1 = 60 requests/minute per authenticated user (or IP when unauthenticated) — a baseline
        // cap so a leaked token can't scrape or hammer the whole API unthrottled. Inline (not a named limiter)
        // so it works without the host registering an `api` RateLimiter.
        'middleware' => ['auth:sanctum', 'throttle:60,1'],
        'per_page' => 25,
        // Hard cap on ?per_page= so a client can't request an unbounded page.
        'max_per_page' => 100,
        // Passport password-grant client used by /api/login (admin-core:install --api-auth).
        // Created with `php artisan passport:client --password` — secret stays server-side.
        'password_client_id' => env('PASSPORT_PASSWORD_CLIENT_ID'),
        'password_client_secret' => env('PASSPORT_PASSWORD_CLIENT_SECRET'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Generator
    |--------------------------------------------------------------------------
    | uuid: the *hybrid* key strategy — a fast bigint `id` primary key (lean
    | foreign keys + joins) plus a unique public `uuid` column used in URLs/APIs
    | (non-enumerable). ON BY DEFAULT: this is the framework standard (the same
    | key strategy admin-core's own tables use), so generated resources are
    | non-enumerable and API-consistent out of the box. Opt out per-resource
    | with --no-uuid (high-volume pivot/log/event tables that never appear in a
    | URL), or app-wide by setting this to false.
    |
    | soft_deletes: when true, every generated resource gets a `deleted_at` column,
    | the SoftDeletes trait + a trash/restore screen. Override per-resource with the
    | --soft-deletes / --no-soft-deletes flags (use --no-soft-deletes for high-churn
    | tables like sale lines or ledger rows that should hard-delete).
    |
    | audit: when true, generated models get the LogsActivity trait (writes
    | created/updated/deleted to the activity log). Override with --audit.
    |
    | base_model: the class generated models extend. Default is Eloquent's Model.
    | If many of your models share behavior, point this at your own base, e.g.
    | App\Models\BaseModel that `use`s the shared traits/casts — then every
    | `admin-core:make` model extends it (keep the *logic* in traits so Spatie's
    | Role/Permission can `use` it too; the base model just bundles them).
    */
    'generator' => [
        'uuid' => true,
        'soft_deletes' => false,
        'audit' => false,
        'base_model' => \Illuminate\Database\Eloquent\Model::class,
    ],

    /*
    |--------------------------------------------------------------------------
    | Explicit NONE for a missing display label (RFC-0009 Rev 2) — compatibility flag
    |--------------------------------------------------------------------------
    |
    | How a RELATED model that has NO human label column (no `name` / `title` /
    | `label`, and no `displayColumn()` override) renders in a list / show / API
    | relation cell.
    |
    |   true   (DEFAULT since v3.0.0) — such a label resolves to NONE: the cell
    |            renders empty instead of leaking a route key. It affects ONLY the
    |            label shown for a genuinely label-less related model — never a
    |            `computed` label (whose accessor is a real value), and never the
    |            descriptor, search, or sort.
    |
    |   false  (DEPRECATED opt-out) — restore the pre-v3.0.0 behavior: fall back to
    |            the model's route key, so the cell shows its id / uuid. Provided as
    |            a temporary migration escape hatch; it will be REMOVED in a future
    |            major (RFC-0009 Rev 2: "deprecate then remove").
    |
    | v3.0.0 flipped this default from false to true (a MAJOR behavior change). Set
    | it to false only to defer the change while you give label-less related models a
    | real label column (`name`/`title`/`label`) or a `displayColumn()` override.
    |
    */
    'explicit_none' => env('ADMIN_CORE_EXPLICIT_NONE', true),

];
