<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Route conventions
    |--------------------------------------------------------------------------
    | name_prefix is prepended to every CRUD route name generated by the
    | Route::crud() macro and used by CrudController to resolve redirects.
    */
    'route' => [
        'name_prefix' => 'admin.',
    ],

    /*
    |--------------------------------------------------------------------------
    | View conventions
    |--------------------------------------------------------------------------
    | path_prefix is prepended to a controller's $viewPath when resolving the
    | index/create/edit/show Blade views.
    */
    'views' => [
        'path_prefix' => 'backend.pages.',
    ],

    /*
    |--------------------------------------------------------------------------
    | Sidebar menu
    |--------------------------------------------------------------------------
    | The admin sidebar is data-driven: <x-admin-core::sidebar-menu /> renders this
    | array, dropping any item the current user can't reach (its `can` permission
    | fails, or its `route` doesn't exist) and any section header left empty.
    |
    | Item shapes:
    |   ['label' => 'Products', 'route' => 'admin.products.index',
    |    'icon' => 'bi bi-box', 'can' => 'list-product', 'match' => 'admin/products*']
    |   ['header' => 'Access']                                  // a section label
    |   ['label' => 'Access', 'icon' => '…', 'match' => 'admin/x/*',
    |    'children' => [ …items… ]]                             // a collapsible group
    |
    | `admin-core:make` appends new resources at the `admin-core:menu` marker below.
    | (Run `php artisan config:clear` after generating if you cache config.)
    */
    'menu' => [
        ['label' => 'Dashboard', 'route' => 'admin.dashboard', 'icon' => 'bi bi-speedometer2', 'match' => 'admin'],
        // admin-core:menu
        ['header' => 'Access'],
        ['label' => 'Assessments', 'icon' => 'bi bi-people', 'match' => 'admin/assessments/*', 'children' => [
            ['label' => 'Users', 'route' => 'admin.assessments.users.index', 'icon' => 'bi bi-person', 'can' => 'list-user', 'match' => 'admin/assessments/users*'],
            ['label' => 'Roles', 'route' => 'admin.assessments.roles.index', 'icon' => 'bi bi-shield-lock', 'can' => 'list-role', 'match' => 'admin/assessments/roles*'],
            ['label' => 'Group Permissions', 'route' => 'admin.assessments.group_permissions.index', 'icon' => 'bi bi-diagram-3', 'can' => 'list-group-permission', 'match' => 'admin/assessments/group_permissions*'],
            ['label' => 'Permissions', 'route' => 'admin.assessments.permissions.index', 'icon' => 'bi bi-key', 'can' => 'list-permission', 'match' => 'admin/assessments/permissions*'],
        ]],
        ['header' => 'System'],
        ['label' => 'Settings', 'route' => 'admin.settings.index', 'icon' => 'bi bi-gear', 'can' => 'manage-settings', 'match' => 'admin/settings*'],
        ['label' => 'Activity Log', 'route' => 'admin.activity-logs.index', 'icon' => 'bi bi-clock-history', 'can' => 'list-activity', 'match' => 'admin/activity-logs*'],
        ['label' => 'Error Log', 'route' => 'admin.error-logs.index', 'icon' => 'bi bi-bug', 'can' => 'view-error-log', 'match' => 'admin/error-logs*'],
        ['label' => 'Menu', 'route' => 'admin.menu.index', 'icon' => 'bi bi-list-nested', 'can' => 'manage-menu', 'match' => 'admin/menu*'],
        ['label' => 'Documentation', 'route' => 'admin.docs', 'icon' => 'bi bi-book', 'match' => 'admin/docs'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Sidebar menu source
    |--------------------------------------------------------------------------
    | 'config'   (default) — render the `menu` array above.
    | 'database' — render the menu_items table managed at /admin/menu (the Menu
    |              manager, shipped by --access) via <x-admin-core::sidebar-menu>,
    |              cached and permission/route-filtered exactly like the config menu.
    |
    | Switching keeps everything else the same. Seed the table from your current
    | array with:  php artisan admin-core:menu:import
    */
    'menu_source' => env('ADMIN_CORE_MENU_SOURCE', 'config'),

    /*
    |--------------------------------------------------------------------------
    | Extra portals (named menus) — multi-portal
    |--------------------------------------------------------------------------
    | A second admin area (merchant, vendor, reseller, …) renders its own menu with
    | <x-admin-core::sidebar-menu menu="merchant" guard="merchant" />. Pass the portal's
    | auth `guard` so the `can` checks run against that portal's user. Each named menu
    | keeps its own `// admin-core:menu:<name>` marker, which `admin-core:make
    | Order --menu=merchant` appends to. Uncomment and tailor to your portals:
    */
    'menus' => [
        // 'merchant' => [
        //     ['label' => 'Dashboard', 'route' => 'merchant.dashboard', 'icon' => 'bi bi-shop', 'match' => 'merchant'],
        //     // admin-core:menu:merchant
        // ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Permission gating
    |--------------------------------------------------------------------------
    | When enabled, the Route::crud() macro wraps each action in a
    | `permission:{action}-{resource}` middleware (e.g. list-user, create-user),
    | and admin-core:make creates the matching permission rows via `model`.
    | Set enabled to false to register routes without permission middleware.
    */
    'permission' => [
        'enabled' => true,
        'pattern' => '{action}-{resource}',
        'model' => \Spatie\Permission\Models\Permission::class,
        'role_model' => \Spatie\Permission\Models\Role::class,
        // admin-core:make grants each new resource's permissions to this role so
        // it's usable immediately (no AccessSeeder re-run). Set null to disable.
        'super_role' => 'admin',
        // Default guard for generated permissions + route gates. `admin-core:make --guard=…`
        // overrides per resource (multi-portal). Spatie scopes permissions by guard.
        'guard' => 'web',
        // Per-guard overrides for separate-portal guards. Spatie requires the super role to
        // be on the same guard as the permission, so a portal can name its own:
        //   'guards' => ['merchant' => ['super_role' => 'merchant-admin']],
        'guards' => [],
    ],

    /*
    |--------------------------------------------------------------------------
    | Default DataTables page length
    |--------------------------------------------------------------------------
    */
    'pagination' => 50,

    /*
    |--------------------------------------------------------------------------
    | Global search (<x-admin-core::global-search /> + Route::adminCoreSearch())
    |--------------------------------------------------------------------------
    | A dependency-free, offline-friendly LIKE search across the resources you list here — no Scout /
    | external engine. Add the topbar box with <x-admin-core::global-search /> and call
    | Route::adminCoreSearch() inside your admin route group. Each entry:
    |   ['model' => \App\Models\Product::class, 'columns' => ['name'], 'label' => 'Products',
    |    'route' => 'admin.products.edit', 'key' => 'uuid', 'icon' => 'bi bi-box-seam']
    | columns are LIKE-matched (a translatable JSON column works — its text is matched, label uses the
    | active locale); route+key build the result link (key defaults to the model's primary key).
    */
    'search' => [],

    /*
    |--------------------------------------------------------------------------
    | Notifications
    |--------------------------------------------------------------------------
    | In-app notifications are always on (the bell + /admin/notifications, Laravel
    | database notifications). Set `realtime` to true to ALSO broadcast each
    | AdminNotification so the bell updates live + a toast pops on arrival — this
    | needs a broadcaster (Reverb/Pusher) + Laravel Echo + a running queue worker.
    | See the "Realtime notifications" section in the README. Per-notification
    | override: new AdminNotification(..., broadcast: true|false).
    */
    'notifications' => [
        'realtime' => env('ADMIN_CORE_REALTIME', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Uploads (images & files) — compression + storage/CDN
    |--------------------------------------------------------------------------
    | All image/file uploads (avatars, `image`/`file` fields, settings images) go
    | through Ngos\AdminCore\Support\Media, so storage + URLs are configured here.
    |
    | disk      : filesystem disk to store on (config/filesystems.php). Point it at
    |             s3 (+ CloudFront) to serve from a CDN automatically.
    | cdn_url   : optional absolute base URL prepended to stored paths when building
    |             URLs (front your storage with a CDN without changing the disk).
    |             Overrides the disk's own url(). e.g. https://cdn.example.com
    | compress  : re-encode uploaded images to WebP (best size at high quality).
    |             Falls back to storing the original if encoding isn't possible.
    | max_width : downscale images wider than this (px) before encoding; 0 = no cap.
    | quality   : WebP quality (0–100); ~82 is visually lossless at a big size saving.
    */
    'uploads' => [
        'disk' => env('ADMIN_CORE_UPLOAD_DISK', 'public'),
        'cdn_url' => env('ADMIN_CORE_CDN_URL'),
        'compress' => true,
        'max_width' => 1600,
        'quality' => 82,
    ],

    /*
    |--------------------------------------------------------------------------
    | Translation & multi-language
    |--------------------------------------------------------------------------
    | Two features, both driven by middleware (no public translate endpoint):
    |
    |  • Per-user UI language — SetLocale middleware picks the active language from
    |    the signed-in user's `locale` (when a `users.locale` column exists), else
    |    the session, else `default`. Users switch via a link `?setlang=km`, which
    |    the same middleware persists. So one admin runs in English, another in
    |    Khmer, each remembered per user.
    |
    |  • Content auto-translate — AutoTranslate middleware fills empty per-locale
    |    fields on save (e.g. you type a product name in Khmer, English/Thai/… are
    |    filled in for you). It never overwrites what you typed, and runs INSIDE the
    |    authenticated, CSRF-protected form submit — no extra endpoint to secure.
    |
    | locales : every language the admin offers — add as many as you like. The key
    |           is the ISO code used by Laravel + the translator (en, km, th, vi, zh…).
    | driver  : which translation backend to use. `mymemory` is free + needs no key.
    |           `libretranslate` (self-host) keeps data on your own servers (private).
    |           `null` disables auto-translate (UI language still works).
    | max_length / rate_limit / timeout : safety limits for outbound translate calls.
    | API keys live here (from env), server-side only — never exposed to the browser.
    */
    'translation' => [
        'enabled' => env('ADMIN_CORE_TRANSLATION', true),
        'driver' => env('ADMIN_CORE_TRANSLATOR', 'mymemory'), // mymemory | libretranslate | null
        'default' => env('ADMIN_CORE_LOCALE', 'en'),
        'locales' => [
            'en' => 'English',
            'km' => 'ខ្មែរ',
            // 'th' => 'ไทย', 'vi' => 'Tiếng Việt', 'zh' => '中文', 'fr' => 'Français',
        ],
        'max_length' => 5000,    // reject translate input longer than this
        'rate_limit' => 60,      // max outbound translate calls per request (guards a runaway save)
        'timeout' => 8,          // seconds per provider call
        'mymemory' => [
            'email' => env('MYMEMORY_EMAIL'), // optional — raises the free daily quota
        ],
        'libretranslate' => [
            'url' => env('LIBRETRANSLATE_URL', 'https://libretranslate.com'),
            'key' => env('LIBRETRANSLATE_KEY'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Error log retention (--access)
    |--------------------------------------------------------------------------
    | Captured exceptions older than this many days are pruned. The package
    | registers a daily `model:prune` for the ErrorLog model, so this needs the
    | app's scheduler running (`schedule:run` via cron). Set to 0 to keep errors
    | forever (no pruning). You can also prune on demand:
    |   php artisan model:prune --model="Ngos\AdminCore\Models\ErrorLog"
    */
    'error_log' => [
        'retention_days' => 30,
    ],

    /*
    |--------------------------------------------------------------------------
    | API (--api)
    |--------------------------------------------------------------------------
    | Resources generated with --api expose a JSON API (JsonResource + apiResource
    | routes) for a decoupled front-end (Nuxt, mobile, …). The public identifier is
    | always the uuid route key, never the bigint id. `middleware` guards every API
    | route — Sanctum by default; add a tenant-scoping middleware here for a
    | multi-tenant setup. `per_page` is the default index page size (override with
    | ?per_page=).
    */
    'api' => [
        'middleware' => ['auth:sanctum'],
        'per_page' => 25,
        // Hard cap on ?per_page= so a client can't request an unbounded page.
        'max_per_page' => 100,
        // Passport password-grant client used by /api/login (admin-core:install --api-auth).
        // Created with `php artisan passport:client --password` — secret stays server-side.
        'password_client_id' => env('PASSPORT_PASSWORD_CLIENT_ID'),
        'password_client_secret' => env('PASSPORT_PASSWORD_CLIENT_SECRET'),
    ],

    /*
    |--------------------------------------------------------------------------
    | Generator
    |--------------------------------------------------------------------------
    | uuid: when true, `admin-core:make` uses the *hybrid* key strategy — a fast
    | bigint `id` primary key (lean foreign keys + joins) plus a unique public
    | `uuid` column used in URLs/APIs (non-enumerable). Override per-resource with
    | the --uuid / --no-uuid flags.
    |
    | soft_deletes: when true, every generated resource gets a `deleted_at` column,
    | the SoftDeletes trait + a trash/restore screen. Override per-resource with the
    | --soft-deletes / --no-soft-deletes flags (use --no-soft-deletes for high-churn
    | tables like sale lines or ledger rows that should hard-delete).
    |
    | audit: when true, generated models get the LogsActivity trait (writes
    | created/updated/deleted to the activity log). Override with --audit.
    |
    | base_model: the class generated models extend. Default is Eloquent's Model.
    | If many of your models share behavior, point this at your own base, e.g.
    | App\Models\BaseModel that `use`s the shared traits/casts — then every
    | `admin-core:make` model extends it (keep the *logic* in traits so Spatie's
    | Role/Permission can `use` it too; the base model just bundles them).
    */
    'generator' => [
        'uuid' => false,
        'soft_deletes' => false,
        'audit' => false,
        'base_model' => \Illuminate\Database\Eloquent\Model::class,
    ],

];
