<?php

namespace Ngos\AdminCore\Console;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Ngos\AdminCore\Translation\TranslationManager;
use Ngos\AdminCore\Translation\Translator;

/**
 * Generate a translated admin-core UI language file for a new locale by machine-translating the English
 * source through the configured translator (MyMemory by default). Writes to the app's override path
 * (`lang/vendor/admin-core/<locale>/admin-core.php`) so it overrides the package strings; existing
 * translations are kept (re-translate with --force). Review the machine output before relying on it.
 *
 *   php artisan admin-core:translate th
 *   php artisan admin-core:translate vi --source=en --force
 */
class AdminCoreTranslateCommand extends Command
{
    protected $signature = 'admin-core:translate {locale : Target language ISO code, e.g. th}
                            {--source=en : Source locale to translate from}
                            {--force : Re-translate keys that already exist in the target file}';

    protected $description = 'Generate a translated admin-core UI language file by machine-translating the source locale.';

    protected int $translatedCount = 0;

    public function handle(TranslationManager $manager): int
    {
        $locale = (string) $this->argument('locale');
        $source = (string) $this->option('source');

        $sourcePath = __DIR__ . '/../../lang/' . $source . '/admin-core.php';
        if (! File::exists($sourcePath)) {
            $this->error("Source language file not found: lang/{$source}/admin-core.php");

            return self::FAILURE;
        }

        $sourceStrings = require $sourcePath;
        if (! is_array($sourceStrings)) {
            $this->error('Source language file did not return an array.');

            return self::FAILURE;
        }

        $driverName = (string) config('admin-core.translation.driver', 'mymemory');
        if ($driverName === 'null') {
            $this->error("translation.driver is 'null' — set ADMIN_CORE_TRANSLATOR (e.g. mymemory) before running.");

            return self::FAILURE;
        }

        $targetPath = lang_path("vendor/admin-core/{$locale}/admin-core.php");
        $existing = [];
        if (File::exists($targetPath)) {
            $loaded = require $targetPath;
            $existing = is_array($loaded) ? $loaded : [];
        }

        $this->info("Translating admin-core UI strings {$source} → {$locale} via {$driverName} …");

        $translated = $this->translateTree($sourceStrings, $existing, $manager->make($driverName), $source, $locale);

        File::ensureDirectoryExists(dirname($targetPath));
        File::put($targetPath, $this->export($translated));

        $this->info("Wrote {$this->translatedCount} translation(s) → {$targetPath}");
        $this->line("Next: add '{$locale}' to config('admin-core.translation.locales') to show it in the switcher. Review the output — machine translation is a draft.");

        return self::SUCCESS;
    }

    /**
     * Walk the source array, translating each string leaf into $to. Nested arrays recurse; an existing
     * non-empty translation is kept unless --force.
     *
     * @param  array<string, mixed>  $source
     * @param  array<string, mixed>  $existing
     * @return array<string, mixed>
     */
    protected function translateTree(array $source, array $existing, Translator $translator, string $from, string $to): array
    {
        $out = [];

        foreach ($source as $key => $value) {
            $current = $existing[$key] ?? null;

            if (is_array($value)) {
                $out[$key] = $this->translateTree($value, is_array($current) ? $current : [], $translator, $from, $to);
            } elseif (is_string($value)) {
                if (preg_match('/:\w|[{}]/', $value)) {
                    // Never machine-translate a string carrying a Laravel placeholder (:name) or {…} token —
                    // the provider mangles it (e.g. ":seconds" → ": secondes") and breaks runtime substitution.
                    // Keep any existing translation, else copy the source verbatim for manual translation.
                    $out[$key] = is_string($current) && trim($current) !== '' ? $current : $value;
                } elseif (! $this->option('force') && is_string($current) && trim($current) !== '') {
                    $out[$key] = $current; // keep an existing translation
                } else {
                    $out[$key] = $translator->translate($value, $from, $to);
                    $this->translatedCount++;
                }
            } else {
                $out[$key] = $value;
            }
        }

        return $out;
    }

    /** @param  array<string, mixed>  $data */
    protected function export(array $data): string
    {
        return "<?php\n\n"
            . "// Generated by `php artisan admin-core:translate`. Machine translation — review before relying on it.\n"
            . 'return ' . $this->arr($data, 0) . ";\n";
    }

    /** @param  array<string, mixed>  $data */
    protected function arr(array $data, int $depth): string
    {
        $pad = str_repeat('    ', $depth + 1);
        $close = str_repeat('    ', $depth);
        $lines = [];

        foreach ($data as $key => $value) {
            $k = var_export($key, true);
            $v = is_array($value) ? $this->arr($value, $depth + 1) : var_export($value, true);
            $lines[] = "{$pad}{$k} => {$v},";
        }

        return "[\n" . implode("\n", $lines) . "\n{$close}]";
    }
}
